# Generated by Django 2.1 on 2018-08-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.CharField(default='Bob', max_length=100),
            preserve_default=False,
        ),
    ]
