# Generated by Django 2.1 on 2018-08-22 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20180822_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='price',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='year',
        ),
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=10, default=4, max_digits=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
