# Generated by Django 2.1 on 2018-08-23 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_car_make'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='make',
        ),
    ]
