# Generated by Django 2.1 on 2018-08-23 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_remove_car_make'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='make',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars.CarMake'),
            preserve_default=False,
        ),
    ]
